# Generated by Django 3.2.6 on 2021-09-13 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_user_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=70, verbose_name='Direccion')),
                ('latitud', models.CharField(max_length=50, null=True, verbose_name='Latitud')),
                ('longitud', models.CharField(max_length=50, null=True, verbose_name='Longitud')),
                ('hora_inicio', models.TimeField(null=True)),
                ('hora_final', models.TimeField(null=True)),
                ('image', models.ImageField(default='default-image.png', upload_to='media\\canchas\\image', verbose_name=True)),
                ('ciudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.ciudad', verbose_name='Ciudad')),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.departamento', verbose_name='Departamento')),
                ('encargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.perfilempresa')),
            ],
        ),
    ]
