# Generated by Django 3.2.6 on 2021-09-18 16:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='empresa',
            name='image',
            field=models.ImageField(default='canchas\\image\\default-image.png', upload_to='media\\canchas\\image', verbose_name=True),
        ),
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('jugadores', models.IntegerField(validators=[django.core.validators.MaxValueValidator(11)], verbose_name='Numero de jugadores')),
                ('image', models.ImageField(default='canchas\\image\\default-image.png', upload_to='media\\canchas\\image', verbose_name='Imagen')),
                ('cancha_conformada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='canchas.cancha', verbose_name='Canchas que conforman cancha')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.empresa')),
            ],
        ),
    ]
