# Generated by Django 3.2.6 on 2021-09-18 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_groups'),
        ('canchas', '0002_auto_20210918_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservas',
            name='Estado',
            field=models.IntegerField(choices=[(0, 'Disponible'), (1, 'En confirmacion'), (2, 'Confirmada'), (3, 'Cancelada')], default=0),
        ),
        migrations.AddField(
            model_name='reservas',
            name='cancha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='canchas.cancha'),
        ),
        migrations.AddField(
            model_name='reservas',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Fecha y Hora'),
        ),
        migrations.AddField(
            model_name='reservas',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.perfilcliente'),
        ),
    ]
