# Generated by Django 3.2.6 on 2021-09-18 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_groups'),
        ('canchas', '0003_auto_20210918_1601'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservas',
            new_name='Reserva',
        ),
        migrations.AlterField(
            model_name='cancha',
            name='cancha_conformada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='canchas.cancha', verbose_name='Canchas que conforman cancha'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(default='Nombre Empresa', max_length=40, verbose_name='Nombre'),
        ),
    ]
