# Generated by Django 3.2.6 on 2021-09-18 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_groups'),
        ('canchas', '0004_auto_20210918_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='Estado',
            field=models.IntegerField(choices=[(0, 'Disponible'), (1, 'En confirmacion'), (2, 'Confirmada'), (3, 'Cancelada'), (4, 'Finalizada')], default=0),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.perfilcliente'),
        ),
    ]
