# Generated by Django 3.2.6 on 2021-09-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0005_auto_20210918_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='slug',
            field=models.SlugField(default='11canchita', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cancha',
            name='slug',
            field=models.SlugField(default='12cancha', unique=True, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
