# Generated by Django 3.2.6 on 2021-09-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0006_auto_20210918_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cancha',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='latitud',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='longitud',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
    ]
