# Generated by Django 3.2.6 on 2021-09-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0007_auto_20210918_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='descripcion',
            field=models.CharField(default='No seeeeeeeeeeeeeeeeeeeeeeeeee jajajajaj jejeje', max_length=120, verbose_name='Descripcion'),
            preserve_default=False,
        ),
    ]
