# Generated by Django 3.2.6 on 2021-09-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0010_auto_20210919_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
    ]
