# Generated by Django 3.2.7 on 2021-09-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0011_alter_cancha_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='image',
            field=models.ImageField(default='canchas/image/default-image.png', upload_to='media/canchas/image', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='image',
            field=models.ImageField(default='canchas/image/default-image.png', upload_to='media/canchas/image', verbose_name=True),
        ),
    ]
