# Generated by Django 3.2.7 on 2021-09-20 01:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0012_auto_20210920_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(default=1, max_length=10, validators=[django.core.validators.RegexValidator(message='Por favor escribe el numero en el formato aceptado sin código de área ej: 3123456789', regex='^(3)([0-9]){9}$')], verbose_name='Telefono'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empresa',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
    ]
