# Generated by Django 3.2.7 on 2021-09-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0014_auto_20210920_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='descripcion',
            field=models.TextField(max_length=250, verbose_name='Descripcion'),
        ),
    ]
