# Generated by Django 3.2.6 on 2021-09-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0017_auto_20210920_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='jugadores',
            field=models.IntegerField(choices=[(5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11')], default=5, verbose_name='Numero de jugadores'),
        ),
    ]
