# Generated by Django 3.2.6 on 2021-09-20 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0019_auto_20210920_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cancha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canchas.cancha'),
        ),
    ]
