# Generated by Django 3.2.6 on 2021-09-20 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210920_0144'),
        ('canchas', '0020_alter_reserva_cancha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.perfilempresa'),
        ),
    ]
