# Generated by Django 3.2.6 on 2021-09-20 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0022_alter_empresa_encargado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='slug',
        ),
    ]
