# Generated by Django 3.2.6 on 2021-09-22 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0024_remove_cancha_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='canchas.empresa'),
        ),
    ]
