# Generated by Django 3.2.7 on 2021-09-20 01:15

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilmoderador',
            name='image',
            field=models.ImageField(default='profiles/image/default-profile.png', upload_to=users.models.custom_upload_to),
        ),
    ]
