# Generated by Django 3.2.7 on 2021-09-20 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_perfilmoderador_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilmoderador',
            name='image',
        ),
    ]
