# Generated by Django 3.2.7 on 2021-09-20 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_perfilmoderador_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcliente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfilcliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfilempresa',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfilempresa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfilmoderador',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfilmoderador', to=settings.AUTH_USER_MODEL),
        ),
    ]
