# Generated by Django 3.2.6 on 2021-08-31 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_alter_perfilusuario_tipo_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre Usuario')),
                ('apellido', models.CharField(max_length=80, verbose_name='Apellido Usuario')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to=users.models.custom_upload_to)),
                ('telefono', models.CharField(max_length=10, verbose_name='Numero telefonico')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
    ]
