# Generated by Django 3.2.6 on 2021-09-02 00:33

import django.core.validators
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210831_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilcliente',
            name='direccion',
            field=models.CharField(default='La casa de lolo', max_length=70, verbose_name='Direccion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='documento',
            field=models.CharField(default='123', max_length=12, verbose_name='Numero de documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='image',
            field=models.ImageField(default='profiles/image/default-profile.png', upload_to=users.models.custom_upload_to),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Por favor escribe el numero en el formato aceptado sin codigo de area ej: 3123456789', regex='^(3)([0-9]){9}$')], verbose_name='Telefono'),
        ),
    ]
