# Generated by Django 3.2.6 on 2021-09-02 00:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_perfilcliente_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcliente',
            name='documento',
            field=models.IntegerField(max_length=12, validators=[django.core.validators.RegexValidator(regex='^[0-9]{13}$')], verbose_name='Numero de documento'),
        ),
    ]
