# Generated by Django 3.2.6 on 2021-09-02 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210902_1717'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ciudade',
            new_name='Ciudad',
        ),
    ]
