# Generated by Django 3.2.6 on 2021-09-04 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210904_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilcliente',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ciudad'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.departamento'),
        ),
    ]
